### ISSUE TITLE
ご確認をお願い致します。

### ISSUE THREAD

**Issue by Stereoarts** [makochang/ROB_BOT#1]
お手数をお掛けして申し訳ありません、許可されていないコード、イメージ、ドキュメントを含んだ状態でのプロジェクトのアップロードはお控え頂けるよう、お願いします。（プロジェクトの一旦削除をお願い致します。）

また、モデル・モーションについては、作者の明示的な同意を得ない限りは、パブリックスペースでの再配布及びゲームエンジンでの使用はしないでください。（明文化されていない限りは、同意を必須としています。）

**Comment by makochang** [comment]
ご連絡ありがとうございます。リポジトリ自体、削除いたします。
